yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='first'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow, name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.models import CreatedModel
from posts.constants import MAX_LEN_OF_STRING as MAX_LEN

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Заголовок группы', max_length=200)
    description = models.TextField('Описание группы')
    slug = models.SlugField('Адрес для страницы с задачей', unique=True)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField('Текст поста', help_text='Введите текст поста')
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    pub_date = models.DateTimeField(
        'Дата создания',
        auto_now_add=True,
        db_index=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:MAX_LEN]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField('Текст комментария')

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text


class Follow(CreatedModel):
    user = models.ForeignKey(
        User,

        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=(
                'user', 'author'), name='unique_follow'),
            models.CheckConstraint(check=~models.Q(user=models.F(
                'author')), name='dont_follow_your_self'),
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.views.decorators.cache import cache_page

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from .utils import pager_list
from posts.constants import VIEW_LIST_COUNT_OF_PAGINATOR as VIEW_LIST


@cache_page(20, key_prefix='index_page')
def index(request):
    '''Вьювс главной страницы: постранично по десять публикаций.'''
    template = 'posts/index.html'
    post_list = Post.objects.select_related('group')
    page_obj = pager_list(request, post_list, VIEW_LIST)
    context = {
        'page_obj': page_obj,
    }

    return render(request, template, context)


def group_posts(request, slug):
    '''Вьювс групп: постранично по десять публикаций группы.'''
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author')
    page_obj = pager_list(request, post_list, VIEW_LIST)
    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, template, context)


def profile(request, username):
    '''Вьювс автора: постранично по десять публикаций.'''
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    following = False
    if request.user.is_authenticated:
        following = request.user.follower.filter(author=author).exists()
    post_list = author.posts.all()
    page_obj = pager_list(request, post_list, VIEW_LIST)
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }

    return render(request, template, context)


def post_detail(request, post_id):
    '''Вьювс публикации.'''
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }

    return render(request, template, context)


@login_required
def post_create(request):
    '''Вьювс создание нового поста.'''
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', post.author)
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    '''Вьювс редактирование поста.'''
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    author = post.author
    is_edit = True
    if author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        cache.clear()
        return redirect('posts:post_detail', post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': is_edit,
    }

    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    '''Вьювс добавления комментария'''
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    '''Посты, на которых подписан пользователь:
        постранично по десять публикаций.'''
    template = 'posts/follow.html'
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = pager_list(request, post_list, VIEW_LIST)
    context = {
        'page_obj': page_obj,
    }

    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user == author or request.user.follower.filter(
            author=author).exists():
        return redirect('posts:profile', author.username)
    Follow.objects.create(author=author, user=request.user)

    return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        author__username=username, user=request.user).delete()

    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
  {% block title %} 
  {% if is_edit %}
    <title>Редактировать запись</title>
  {% else %}
  <title>Добавить запись</title>
  {% endif %}
  {% endblock %} 

  {% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">   
                {% if is_edit %}    
                  Редактировать пост 
                {% else %}   
                  Новый пост
                {% endif %}
              </div>
              <div class="card-body">  
                {% load user_filters %}
                {% include 'includes/form_error.html' %}

                <form method="post" action=
                {% if is_edit %}
                  "{% url 'posts:post_edit' post.id %}"
                {% else %}
                  "{% url 'posts:post_create' %}"
                {% endif %}
                enctype="multipart/form-data"
                >

                  {% csrf_token %}
                             
                  {% for field in form %}
                    {% include 'includes/form.html' %}
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
  {% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
  {% block title %} 
    <title>Избранные авторы</title>
  {% endblock %} 

  {% block content %}
    <h1>Избранные авторы</h1>
    <h3>Всего у пользователя подписок: {{ user.follower.count }} </h3>
    {% if page_obj.has_other_pages %}
      {% include 'posts/includes/paginator.html' %} 
    {% endif %}
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
    {% endfor %} 
  {% endblock %}     

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
  {% block title %} 
    <title>
      Записи сообщества {{ group.title }}
    </title>
  {% endblock %}

  {% block content %}
    <h1> {{ group.title }} </h1>
    <p>{{ group.description }}</p>
    {% if page_obj.has_other_pages %}
      {% include 'posts/includes/paginator.html' %} 
    {% endif %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
    {% endfor %}
  {% endblock %}
  

yatube/templates/posts/index.html
{% extends 'base.html' %}
  {% block title %} 
    <title>Последние обновления на сайте</title>
  {% endblock %} 

  {% block content %}
    <h1>Последние обновления на сайте</h1>
    {% if page_obj.has_other_pages %}
      {% include 'posts/includes/paginator.html' %} 
    {% endif %}
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_list.html' %}
    {% endfor %} 
  {% endblock %}     

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
  {% block title %} 
    <title>Пост {{ post.text|truncatechars:30 }}</title>
  {% endblock %}

  {% block content %}
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
          {% if post.group %}  
            <li class="list-group-item">
              Группа: {{ post.group.title }} 
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>  
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p> {{ post.text|linebreaksbr }} </p>
        {% if post.author == request.user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать запись
          </a>
          {% endif %}

          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
          {% endif %}
        
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
              <p>
                {{ comment }}
              </p>
            </div>
          </div>
        {% endfor %}
      </article>
    </div> 
  {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
  {% block title %} 
    <title>
      Профайл пользователя {{ author.get_full_name }} 
    </title>
  {% endblock %} 

  {% block content %}       
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    <h3>Всего подписчиков у автора: {{ author.following.count }} </h3>
    <p>Всего у пользователя подписок: {{ user.follower.count }} </p>
    {% if user.is_authenticated and user != author %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    {% endif %}
    {% for post in page_obj %}  
      {% include 'posts/includes/post_list.html' %} 
    {% endfor %}  
  {% endblock %}